@baseUrl = http://localhost:3001
@contentType = application/json




### Create a Account
GET {{baseUrl}}/auth/sign-in
Content-Type: {{contentType}}
{
    "email": "gs.montanher@gmail.com",
    "password": "123456"
}